// Code generated by protoc-gen-go. DO NOT EDIT.
// source: group-msg.proto

package pb_user_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GroupResponse 用户组响应
type GroupResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupResponse) Reset()         { *m = GroupResponse{} }
func (m *GroupResponse) String() string { return proto.CompactTextString(m) }
func (*GroupResponse) ProtoMessage()    {}
func (*GroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c865a28f9475e1af, []int{0}
}

func (m *GroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupResponse.Unmarshal(m, b)
}
func (m *GroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupResponse.Marshal(b, m, deterministic)
}
func (m *GroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupResponse.Merge(m, src)
}
func (m *GroupResponse) XXX_Size() int {
	return xxx_messageInfo_GroupResponse.Size(m)
}
func (m *GroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupResponse proto.InternalMessageInfo

func (m *GroupResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

// GroupID 用户组ID
type GroupID struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupID) Reset()         { *m = GroupID{} }
func (m *GroupID) String() string { return proto.CompactTextString(m) }
func (*GroupID) ProtoMessage()    {}
func (*GroupID) Descriptor() ([]byte, []int) {
	return fileDescriptor_c865a28f9475e1af, []int{1}
}

func (m *GroupID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupID.Unmarshal(m, b)
}
func (m *GroupID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupID.Marshal(b, m, deterministic)
}
func (m *GroupID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupID.Merge(m, src)
}
func (m *GroupID) XXX_Size() int {
	return xxx_messageInfo_GroupID.Size(m)
}
func (m *GroupID) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupID.DiscardUnknown(m)
}

var xxx_messageInfo_GroupID proto.InternalMessageInfo

func (m *GroupID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// quota 配额信息
type Quota struct {
	IsShare              int64    `protobuf:"varint,1,opt,name=is_share,json=isShare,proto3" json:"is_share,omitempty"`
	ResourcesGroupId     string   `protobuf:"bytes,2,opt,name=resources_group_id,json=resourcesGroupId,proto3" json:"resources_group_id,omitempty"`
	Gpu                  int64    `protobuf:"varint,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Cpu                  int64    `protobuf:"varint,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory               int64    `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quota) Reset()         { *m = Quota{} }
func (m *Quota) String() string { return proto.CompactTextString(m) }
func (*Quota) ProtoMessage()    {}
func (*Quota) Descriptor() ([]byte, []int) {
	return fileDescriptor_c865a28f9475e1af, []int{2}
}

func (m *Quota) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quota.Unmarshal(m, b)
}
func (m *Quota) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quota.Marshal(b, m, deterministic)
}
func (m *Quota) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quota.Merge(m, src)
}
func (m *Quota) XXX_Size() int {
	return xxx_messageInfo_Quota.Size(m)
}
func (m *Quota) XXX_DiscardUnknown() {
	xxx_messageInfo_Quota.DiscardUnknown(m)
}

var xxx_messageInfo_Quota proto.InternalMessageInfo

func (m *Quota) GetIsShare() int64 {
	if m != nil {
		return m.IsShare
	}
	return 0
}

func (m *Quota) GetResourcesGroupId() string {
	if m != nil {
		return m.ResourcesGroupId
	}
	return ""
}

func (m *Quota) GetGpu() int64 {
	if m != nil {
		return m.Gpu
	}
	return 0
}

func (m *Quota) GetCpu() int64 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *Quota) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

// group 组信息
type GroupWithQuota struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId             int64    `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	TopParentId          int64    `protobuf:"varint,4,opt,name=top_parent_id,json=topParentId,proto3" json:"top_parent_id,omitempty"`
	DiskQuotaSize        int64    `protobuf:"varint,5,opt,name=disk_quota_size,json=diskQuotaSize,proto3" json:"disk_quota_size,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Quotas               []*Quota `protobuf:"bytes,7,rep,name=quotas,proto3" json:"quotas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupWithQuota) Reset()         { *m = GroupWithQuota{} }
func (m *GroupWithQuota) String() string { return proto.CompactTextString(m) }
func (*GroupWithQuota) ProtoMessage()    {}
func (*GroupWithQuota) Descriptor() ([]byte, []int) {
	return fileDescriptor_c865a28f9475e1af, []int{3}
}

func (m *GroupWithQuota) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupWithQuota.Unmarshal(m, b)
}
func (m *GroupWithQuota) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupWithQuota.Marshal(b, m, deterministic)
}
func (m *GroupWithQuota) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupWithQuota.Merge(m, src)
}
func (m *GroupWithQuota) XXX_Size() int {
	return xxx_messageInfo_GroupWithQuota.Size(m)
}
func (m *GroupWithQuota) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupWithQuota.DiscardUnknown(m)
}

var xxx_messageInfo_GroupWithQuota proto.InternalMessageInfo

func (m *GroupWithQuota) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GroupWithQuota) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupWithQuota) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *GroupWithQuota) GetTopParentId() int64 {
	if m != nil {
		return m.TopParentId
	}
	return 0
}

func (m *GroupWithQuota) GetDiskQuotaSize() int64 {
	if m != nil {
		return m.DiskQuotaSize
	}
	return 0
}

func (m *GroupWithQuota) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GroupWithQuota) GetQuotas() []*Quota {
	if m != nil {
		return m.Quotas
	}
	return nil
}

// GroupAddRequest 用户组添加请求
type GroupAddRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId             int64    `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	DiskQuotaSize        int64    `protobuf:"varint,3,opt,name=disk_quota_size,json=diskQuotaSize,proto3" json:"disk_quota_size,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Quotas               []*Quota `protobuf:"bytes,5,rep,name=quotas,proto3" json:"quotas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupAddRequest) Reset()         { *m = GroupAddRequest{} }
func (m *GroupAddRequest) String() string { return proto.CompactTextString(m) }
func (*GroupAddRequest) ProtoMessage()    {}
func (*GroupAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c865a28f9475e1af, []int{4}
}

func (m *GroupAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupAddRequest.Unmarshal(m, b)
}
func (m *GroupAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupAddRequest.Marshal(b, m, deterministic)
}
func (m *GroupAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupAddRequest.Merge(m, src)
}
func (m *GroupAddRequest) XXX_Size() int {
	return xxx_messageInfo_GroupAddRequest.Size(m)
}
func (m *GroupAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupAddRequest proto.InternalMessageInfo

func (m *GroupAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupAddRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *GroupAddRequest) GetDiskQuotaSize() int64 {
	if m != nil {
		return m.DiskQuotaSize
	}
	return 0
}

func (m *GroupAddRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GroupAddRequest) GetQuotas() []*Quota {
	if m != nil {
		return m.Quotas
	}
	return nil
}

// GroupQueryByConditionRequest 按条件查询组信息请求
type GroupQueryWithQuotaByConditionRequest struct {
	Id                   []int64  `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	Name                 []string `protobuf:"bytes,2,rep,name=name,proto3" json:"name,omitempty"`
	ParentId             []int64  `protobuf:"varint,3,rep,packed,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupQueryWithQuotaByConditionRequest) Reset()         { *m = GroupQueryWithQuotaByConditionRequest{} }
func (m *GroupQueryWithQuotaByConditionRequest) String() string { return proto.CompactTextString(m) }
func (*GroupQueryWithQuotaByConditionRequest) ProtoMessage()    {}
func (*GroupQueryWithQuotaByConditionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c865a28f9475e1af, []int{5}
}

func (m *GroupQueryWithQuotaByConditionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupQueryWithQuotaByConditionRequest.Unmarshal(m, b)
}
func (m *GroupQueryWithQuotaByConditionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupQueryWithQuotaByConditionRequest.Marshal(b, m, deterministic)
}
func (m *GroupQueryWithQuotaByConditionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupQueryWithQuotaByConditionRequest.Merge(m, src)
}
func (m *GroupQueryWithQuotaByConditionRequest) XXX_Size() int {
	return xxx_messageInfo_GroupQueryWithQuotaByConditionRequest.Size(m)
}
func (m *GroupQueryWithQuotaByConditionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupQueryWithQuotaByConditionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupQueryWithQuotaByConditionRequest proto.InternalMessageInfo

func (m *GroupQueryWithQuotaByConditionRequest) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GroupQueryWithQuotaByConditionRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *GroupQueryWithQuotaByConditionRequest) GetParentId() []int64 {
	if m != nil {
		return m.ParentId
	}
	return nil
}

// GroupQueryByConditionResponse 按条件查询组信息响应
type GroupQueryWithQuotaByConditionResponse struct {
	Groups               []*GroupWithQuota `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GroupQueryWithQuotaByConditionResponse) Reset() {
	*m = GroupQueryWithQuotaByConditionResponse{}
}
func (m *GroupQueryWithQuotaByConditionResponse) String() string { return proto.CompactTextString(m) }
func (*GroupQueryWithQuotaByConditionResponse) ProtoMessage()    {}
func (*GroupQueryWithQuotaByConditionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c865a28f9475e1af, []int{6}
}

func (m *GroupQueryWithQuotaByConditionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupQueryWithQuotaByConditionResponse.Unmarshal(m, b)
}
func (m *GroupQueryWithQuotaByConditionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupQueryWithQuotaByConditionResponse.Marshal(b, m, deterministic)
}
func (m *GroupQueryWithQuotaByConditionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupQueryWithQuotaByConditionResponse.Merge(m, src)
}
func (m *GroupQueryWithQuotaByConditionResponse) XXX_Size() int {
	return xxx_messageInfo_GroupQueryWithQuotaByConditionResponse.Size(m)
}
func (m *GroupQueryWithQuotaByConditionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupQueryWithQuotaByConditionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupQueryWithQuotaByConditionResponse proto.InternalMessageInfo

func (m *GroupQueryWithQuotaByConditionResponse) GetGroups() []*GroupWithQuota {
	if m != nil {
		return m.Groups
	}
	return nil
}

// GroupUpdateRequest 组信息更新请求
type GroupUpdateRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId             int64    `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	UseParentId          bool     `protobuf:"varint,4,opt,name=use_parent_id,json=useParentId,proto3" json:"use_parent_id,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Quotas               []*Quota `protobuf:"bytes,6,rep,name=quotas,proto3" json:"quotas,omitempty"`
	DiskQuotaSize        int64    `protobuf:"varint,7,opt,name=disk_quota_size,json=diskQuotaSize,proto3" json:"disk_quota_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupUpdateRequest) Reset()         { *m = GroupUpdateRequest{} }
func (m *GroupUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*GroupUpdateRequest) ProtoMessage()    {}
func (*GroupUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c865a28f9475e1af, []int{7}
}

func (m *GroupUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupUpdateRequest.Unmarshal(m, b)
}
func (m *GroupUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupUpdateRequest.Marshal(b, m, deterministic)
}
func (m *GroupUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupUpdateRequest.Merge(m, src)
}
func (m *GroupUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_GroupUpdateRequest.Size(m)
}
func (m *GroupUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupUpdateRequest proto.InternalMessageInfo

func (m *GroupUpdateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GroupUpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupUpdateRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *GroupUpdateRequest) GetUseParentId() bool {
	if m != nil {
		return m.UseParentId
	}
	return false
}

func (m *GroupUpdateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GroupUpdateRequest) GetQuotas() []*Quota {
	if m != nil {
		return m.Quotas
	}
	return nil
}

func (m *GroupUpdateRequest) GetDiskQuotaSize() int64 {
	if m != nil {
		return m.DiskQuotaSize
	}
	return 0
}

// QuotaUpdateRequest 配额信息更新请求
type QuotaUpdateRequest struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	IsShare              int64    `protobuf:"varint,2,opt,name=is_share,json=isShare,proto3" json:"is_share,omitempty"`
	ResourcesId          string   `protobuf:"bytes,3,opt,name=resources_id,json=resourcesId,proto3" json:"resources_id,omitempty"`
	QuotaType            int64    `protobuf:"varint,4,opt,name=quota_type,json=quotaType,proto3" json:"quota_type,omitempty"`
	Total                int64    `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	Used                 int64    `protobuf:"varint,6,opt,name=used,proto3" json:"used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuotaUpdateRequest) Reset()         { *m = QuotaUpdateRequest{} }
func (m *QuotaUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*QuotaUpdateRequest) ProtoMessage()    {}
func (*QuotaUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c865a28f9475e1af, []int{8}
}

func (m *QuotaUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuotaUpdateRequest.Unmarshal(m, b)
}
func (m *QuotaUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuotaUpdateRequest.Marshal(b, m, deterministic)
}
func (m *QuotaUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuotaUpdateRequest.Merge(m, src)
}
func (m *QuotaUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_QuotaUpdateRequest.Size(m)
}
func (m *QuotaUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuotaUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuotaUpdateRequest proto.InternalMessageInfo

func (m *QuotaUpdateRequest) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *QuotaUpdateRequest) GetIsShare() int64 {
	if m != nil {
		return m.IsShare
	}
	return 0
}

func (m *QuotaUpdateRequest) GetResourcesId() string {
	if m != nil {
		return m.ResourcesId
	}
	return ""
}

func (m *QuotaUpdateRequest) GetQuotaType() int64 {
	if m != nil {
		return m.QuotaType
	}
	return 0
}

func (m *QuotaUpdateRequest) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *QuotaUpdateRequest) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

// SetGroupQuotaRequest 配额信息更新请求
type SetGroupQuotaUsedRequest struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	IsShare              int64    `protobuf:"varint,2,opt,name=is_share,json=isShare,proto3" json:"is_share,omitempty"`
	QuotaType            int64    `protobuf:"varint,3,opt,name=quota_type,json=quotaType,proto3" json:"quota_type,omitempty"`
	Used                 int64    `protobuf:"varint,4,opt,name=used,proto3" json:"used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGroupQuotaUsedRequest) Reset()         { *m = SetGroupQuotaUsedRequest{} }
func (m *SetGroupQuotaUsedRequest) String() string { return proto.CompactTextString(m) }
func (*SetGroupQuotaUsedRequest) ProtoMessage()    {}
func (*SetGroupQuotaUsedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c865a28f9475e1af, []int{9}
}

func (m *SetGroupQuotaUsedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGroupQuotaUsedRequest.Unmarshal(m, b)
}
func (m *SetGroupQuotaUsedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGroupQuotaUsedRequest.Marshal(b, m, deterministic)
}
func (m *SetGroupQuotaUsedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGroupQuotaUsedRequest.Merge(m, src)
}
func (m *SetGroupQuotaUsedRequest) XXX_Size() int {
	return xxx_messageInfo_SetGroupQuotaUsedRequest.Size(m)
}
func (m *SetGroupQuotaUsedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGroupQuotaUsedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetGroupQuotaUsedRequest proto.InternalMessageInfo

func (m *SetGroupQuotaUsedRequest) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *SetGroupQuotaUsedRequest) GetIsShare() int64 {
	if m != nil {
		return m.IsShare
	}
	return 0
}

func (m *SetGroupQuotaUsedRequest) GetQuotaType() int64 {
	if m != nil {
		return m.QuotaType
	}
	return 0
}

func (m *SetGroupQuotaUsedRequest) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

// GroupTreeResponse 组树查询响应
type GroupTreeResponse struct {
	TreeJson             []byte   `protobuf:"bytes,1,opt,name=tree_json,json=treeJson,proto3" json:"tree_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupTreeResponse) Reset()         { *m = GroupTreeResponse{} }
func (m *GroupTreeResponse) String() string { return proto.CompactTextString(m) }
func (*GroupTreeResponse) ProtoMessage()    {}
func (*GroupTreeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c865a28f9475e1af, []int{10}
}

func (m *GroupTreeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupTreeResponse.Unmarshal(m, b)
}
func (m *GroupTreeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupTreeResponse.Marshal(b, m, deterministic)
}
func (m *GroupTreeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupTreeResponse.Merge(m, src)
}
func (m *GroupTreeResponse) XXX_Size() int {
	return xxx_messageInfo_GroupTreeResponse.Size(m)
}
func (m *GroupTreeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupTreeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupTreeResponse proto.InternalMessageInfo

func (m *GroupTreeResponse) GetTreeJson() []byte {
	if m != nil {
		return m.TreeJson
	}
	return nil
}

// GroupIDsResponse 组ID
type GroupIDsResponse struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupIDsResponse) Reset()         { *m = GroupIDsResponse{} }
func (m *GroupIDsResponse) String() string { return proto.CompactTextString(m) }
func (*GroupIDsResponse) ProtoMessage()    {}
func (*GroupIDsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c865a28f9475e1af, []int{11}
}

func (m *GroupIDsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupIDsResponse.Unmarshal(m, b)
}
func (m *GroupIDsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupIDsResponse.Marshal(b, m, deterministic)
}
func (m *GroupIDsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupIDsResponse.Merge(m, src)
}
func (m *GroupIDsResponse) XXX_Size() int {
	return xxx_messageInfo_GroupIDsResponse.Size(m)
}
func (m *GroupIDsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupIDsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupIDsResponse proto.InternalMessageInfo

func (m *GroupIDsResponse) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterType((*GroupResponse)(nil), "pb_user_v1.GroupResponse")
	proto.RegisterType((*GroupID)(nil), "pb_user_v1.GroupID")
	proto.RegisterType((*Quota)(nil), "pb_user_v1.Quota")
	proto.RegisterType((*GroupWithQuota)(nil), "pb_user_v1.GroupWithQuota")
	proto.RegisterType((*GroupAddRequest)(nil), "pb_user_v1.GroupAddRequest")
	proto.RegisterType((*GroupQueryWithQuotaByConditionRequest)(nil), "pb_user_v1.GroupQueryWithQuotaByConditionRequest")
	proto.RegisterType((*GroupQueryWithQuotaByConditionResponse)(nil), "pb_user_v1.GroupQueryWithQuotaByConditionResponse")
	proto.RegisterType((*GroupUpdateRequest)(nil), "pb_user_v1.GroupUpdateRequest")
	proto.RegisterType((*QuotaUpdateRequest)(nil), "pb_user_v1.QuotaUpdateRequest")
	proto.RegisterType((*SetGroupQuotaUsedRequest)(nil), "pb_user_v1.SetGroupQuotaUsedRequest")
	proto.RegisterType((*GroupTreeResponse)(nil), "pb_user_v1.GroupTreeResponse")
	proto.RegisterType((*GroupIDsResponse)(nil), "pb_user_v1.GroupIDsResponse")
}

func init() { proto.RegisterFile("group-msg.proto", fileDescriptor_c865a28f9475e1af) }

var fileDescriptor_c865a28f9475e1af = []byte{
	// 611 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0xe5, 0x38, 0x71, 0x92, 0x71, 0x0f, 0xe9, 0xea, 0xd3, 0x27, 0x97, 0x0a, 0x29, 0x18,
	0xa8, 0x8a, 0x04, 0x15, 0x94, 0x27, 0xe0, 0x20, 0xa1, 0x72, 0x45, 0xdd, 0x22, 0x6e, 0x90, 0x2c,
	0x37, 0x3b, 0x4a, 0x17, 0x88, 0x77, 0xbb, 0x07, 0xa4, 0xf4, 0x96, 0x5b, 0x9e, 0x07, 0xde, 0x89,
	0x0b, 0x9e, 0x01, 0xed, 0x7a, 0xe3, 0x24, 0x26, 0x6d, 0x90, 0x7a, 0xb7, 0x3b, 0x3b, 0x9e, 0xf9,
	0x8d, 0xe7, 0x3f, 0x03, 0xdb, 0x63, 0xc9, 0x8d, 0x78, 0x32, 0x51, 0xe3, 0x43, 0x21, 0xb9, 0xe6,
	0x04, 0xc4, 0x79, 0x6e, 0x14, 0xca, 0xfc, 0xeb, 0xb3, 0xf4, 0x3e, 0x6c, 0xbe, 0xb1, 0xcf, 0x19,
	0x2a, 0xc1, 0x4b, 0x85, 0x84, 0x40, 0x7b, 0xc4, 0x29, 0x26, 0xc1, 0x30, 0x38, 0x08, 0x33, 0x77,
	0x4e, 0x77, 0xa1, 0xeb, 0x9c, 0x8e, 0x5f, 0x93, 0x2d, 0x68, 0x31, 0xea, 0x1f, 0x5b, 0x8c, 0xa6,
	0xdf, 0x03, 0xe8, 0x9c, 0x18, 0xae, 0x0b, 0xb2, 0x0b, 0x3d, 0xa6, 0x72, 0x75, 0x51, 0xc8, 0xd9,
	0xc7, 0x5d, 0xa6, 0x4e, 0xed, 0x95, 0x3c, 0x06, 0x22, 0x51, 0x71, 0x23, 0x47, 0xa8, 0x72, 0x47,
	0x93, 0x33, 0x9a, 0xb4, 0x86, 0xc1, 0x41, 0x3f, 0x1b, 0xd4, 0x2f, 0x55, 0x0a, 0x4a, 0x06, 0x10,
	0x8e, 0x85, 0x49, 0x42, 0x17, 0xc3, 0x1e, 0xad, 0x65, 0x24, 0x4c, 0xd2, 0xae, 0x2c, 0x23, 0x61,
	0xc8, 0xff, 0x10, 0x4d, 0x70, 0xc2, 0xe5, 0x34, 0xe9, 0x38, 0xa3, 0xbf, 0xa5, 0xbf, 0x02, 0xd8,
	0x72, 0x71, 0x3e, 0x30, 0x7d, 0x51, 0x71, 0x35, 0x88, 0x6d, 0x81, 0x65, 0x31, 0x41, 0x9f, 0xde,
	0x9d, 0xc9, 0x1e, 0xf4, 0x45, 0x21, 0xb1, 0xd4, 0x96, 0xab, 0x4a, 0xdc, 0xab, 0x0c, 0xc7, 0x94,
	0xa4, 0xb0, 0xa9, 0xb9, 0xc8, 0xe7, 0x0e, 0x15, 0x47, 0xac, 0xb9, 0x78, 0x37, 0xf3, 0xd9, 0x87,
	0x6d, 0xca, 0xd4, 0xe7, 0xfc, 0xd2, 0xa6, 0xcc, 0x15, 0xbb, 0x42, 0x0f, 0xb6, 0x69, 0xcd, 0x0e,
	0xe4, 0x94, 0x5d, 0x21, 0x19, 0x42, 0x4c, 0x51, 0x8d, 0x24, 0x13, 0x9a, 0xf1, 0x32, 0x89, 0x1c,
	0xc3, 0xa2, 0x89, 0x3c, 0x82, 0xc8, 0x05, 0x51, 0x49, 0x77, 0x18, 0x1e, 0xc4, 0x47, 0x3b, 0x87,
	0xf3, 0x6e, 0x1d, 0xba, 0x40, 0x99, 0x77, 0x48, 0x7f, 0x06, 0xb0, 0xed, 0x8a, 0x7d, 0x41, 0x69,
	0x86, 0x97, 0x06, 0x95, 0xae, 0xab, 0x0b, 0xae, 0xab, 0xae, 0xd5, 0xa8, 0x6e, 0x05, 0x79, 0xf8,
	0x0f, 0xe4, 0xed, 0x9b, 0xc8, 0x3b, 0xeb, 0xc8, 0x2f, 0xe0, 0xa1, 0x03, 0x3f, 0x31, 0x28, 0xa7,
	0x75, 0xab, 0x5e, 0x4e, 0x5f, 0xf1, 0x92, 0x32, 0x1b, 0x6c, 0x56, 0xce, 0xac, 0x79, 0xe1, 0x5f,
	0xcd, 0x0b, 0xaf, 0x6b, 0x5e, 0xb8, 0x58, 0x5e, 0xfa, 0x11, 0xf6, 0xd7, 0x65, 0xf2, 0xc2, 0x3f,
	0x82, 0xc8, 0x49, 0x53, 0xb9, 0x74, 0xf1, 0xd1, 0x9d, 0x45, 0xfc, 0x65, 0x4d, 0x65, 0xde, 0x33,
	0xfd, 0x1d, 0x00, 0x71, 0x4f, 0xef, 0x05, 0x2d, 0x34, 0x36, 0xa9, 0x6f, 0x23, 0x39, 0xa3, 0xb0,
	0x21, 0xb9, 0x5e, 0x16, 0x1b, 0x85, 0xb5, 0xe4, 0x1a, 0x0d, 0xe9, 0xdc, 0xd4, 0x90, 0x68, 0x4d,
	0x43, 0x56, 0xa9, 0xa0, 0xbb, 0x42, 0x05, 0xe9, 0x8f, 0x00, 0x88, 0xbb, 0x2d, 0x17, 0xbc, 0x0b,
	0xbd, 0x7a, 0xac, 0xfd, 0xec, 0x8f, 0xfd, 0x34, 0x2f, 0xae, 0x85, 0xd6, 0xf2, 0x5a, 0xb8, 0x07,
	0x1b, 0xf3, 0xb5, 0xe0, 0xff, 0x42, 0x3f, 0x8b, 0x6b, 0xdb, 0x31, 0x25, 0x77, 0x01, 0x2a, 0x24,
	0x3d, 0x15, 0xe8, 0x07, 0xaf, 0xef, 0x2c, 0x67, 0x53, 0x81, 0xe4, 0x3f, 0xe8, 0x68, 0xae, 0x8b,
	0x2f, 0x7e, 0xd8, 0xaa, 0x8b, 0xfd, 0xdd, 0x46, 0x21, 0x75, 0xd3, 0x15, 0x66, 0xee, 0x9c, 0x7e,
	0x0b, 0x20, 0x39, 0x45, 0xed, 0xb5, 0x60, 0x0b, 0x50, 0x48, 0x6f, 0x87, 0xbf, 0xcc, 0x16, 0x36,
	0xd9, 0x66, 0x14, 0xed, 0x05, 0x8a, 0xa7, 0xb0, 0xe3, 0x08, 0xce, 0x24, 0x62, 0x2d, 0xbc, 0x3d,
	0xe8, 0x6b, 0x89, 0x98, 0x7f, 0x52, 0xbc, 0x74, 0xe9, 0x37, 0xb2, 0x9e, 0x35, 0xbc, 0x55, 0xbc,
	0x4c, 0x1f, 0xc0, 0xc0, 0xaf, 0x5e, 0x55, 0x7f, 0x30, 0x80, 0x90, 0x51, 0xe5, 0xa7, 0xc2, 0x1e,
	0xcf, 0x23, 0xb7, 0xd8, 0x9f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xd8, 0xd8, 0x51, 0xeb,
	0x05, 0x00, 0x00,
}
