// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permission-msg.proto

package pb_user_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Module int32

const (
	Module__Module Module = 0
	//算力云平台
	Module_MODULE_BASIC Module = 1
)

var Module_name = map[int32]string{
	0: "_Module",
	1: "MODULE_BASIC",
}

var Module_value = map[string]int32{
	"_Module":      0,
	"MODULE_BASIC": 1,
}

func (x Module) String() string {
	return proto.EnumName(Module_name, int32(x))
}

func (Module) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_08a373ad122871df, []int{0}
}

type PermissionProto struct {
	Index                *Index   `protobuf:"bytes,9,opt,name=index,proto3" json:"index,omitempty"`
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UriName              string   `protobuf:"bytes,2,opt,name=uri_name,json=uriName,proto3" json:"uri_name,omitempty"`
	Method               int32    `protobuf:"varint,3,opt,name=method,proto3" json:"method,omitempty"`
	Uri                  string   `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	Relation             int32    `protobuf:"varint,5,opt,name=relation,proto3" json:"relation,omitempty"`
	ButtonName           string   `protobuf:"bytes,6,opt,name=button_name,json=buttonName,proto3" json:"button_name,omitempty"`
	ButtonKey            string   `protobuf:"bytes,7,opt,name=button_key,json=buttonKey,proto3" json:"button_key,omitempty"`
	MenuId               int64    `protobuf:"varint,8,opt,name=menu_id,json=menuId,proto3" json:"menu_id,omitempty"`
	Module               int32    `protobuf:"varint,10,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionProto) Reset()         { *m = PermissionProto{} }
func (m *PermissionProto) String() string { return proto.CompactTextString(m) }
func (*PermissionProto) ProtoMessage()    {}
func (*PermissionProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_08a373ad122871df, []int{0}
}

func (m *PermissionProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionProto.Unmarshal(m, b)
}
func (m *PermissionProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionProto.Marshal(b, m, deterministic)
}
func (m *PermissionProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionProto.Merge(m, src)
}
func (m *PermissionProto) XXX_Size() int {
	return xxx_messageInfo_PermissionProto.Size(m)
}
func (m *PermissionProto) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionProto.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionProto proto.InternalMessageInfo

func (m *PermissionProto) GetIndex() *Index {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *PermissionProto) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PermissionProto) GetUriName() string {
	if m != nil {
		return m.UriName
	}
	return ""
}

func (m *PermissionProto) GetMethod() int32 {
	if m != nil {
		return m.Method
	}
	return 0
}

func (m *PermissionProto) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *PermissionProto) GetRelation() int32 {
	if m != nil {
		return m.Relation
	}
	return 0
}

func (m *PermissionProto) GetButtonName() string {
	if m != nil {
		return m.ButtonName
	}
	return ""
}

func (m *PermissionProto) GetButtonKey() string {
	if m != nil {
		return m.ButtonKey
	}
	return ""
}

func (m *PermissionProto) GetMenuId() int64 {
	if m != nil {
		return m.MenuId
	}
	return 0
}

func (m *PermissionProto) GetModule() int32 {
	if m != nil {
		return m.Module
	}
	return 0
}

type MenuProto struct {
	Index                *Index   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParenId              int64    `protobuf:"varint,3,opt,name=paren_id,json=parenId,proto3" json:"paren_id,omitempty"`
	Module               Module   `protobuf:"varint,4,opt,name=module,proto3,enum=pb_user_v1.Module" json:"module,omitempty"`
	Order                int64    `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	TemplatePath         string   `protobuf:"bytes,6,opt,name=template_path,json=templatePath,proto3" json:"template_path,omitempty"`
	UserId               int64    `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuProto) Reset()         { *m = MenuProto{} }
func (m *MenuProto) String() string { return proto.CompactTextString(m) }
func (*MenuProto) ProtoMessage()    {}
func (*MenuProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_08a373ad122871df, []int{1}
}

func (m *MenuProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuProto.Unmarshal(m, b)
}
func (m *MenuProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuProto.Marshal(b, m, deterministic)
}
func (m *MenuProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuProto.Merge(m, src)
}
func (m *MenuProto) XXX_Size() int {
	return xxx_messageInfo_MenuProto.Size(m)
}
func (m *MenuProto) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuProto.DiscardUnknown(m)
}

var xxx_messageInfo_MenuProto proto.InternalMessageInfo

func (m *MenuProto) GetIndex() *Index {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *MenuProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MenuProto) GetParenId() int64 {
	if m != nil {
		return m.ParenId
	}
	return 0
}

func (m *MenuProto) GetModule() Module {
	if m != nil {
		return m.Module
	}
	return Module__Module
}

func (m *MenuProto) GetOrder() int64 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *MenuProto) GetTemplatePath() string {
	if m != nil {
		return m.TemplatePath
	}
	return ""
}

func (m *MenuProto) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type MenuModule struct {
	Module               Module   `protobuf:"varint,1,opt,name=module,proto3,enum=pb_user_v1.Module" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuModule) Reset()         { *m = MenuModule{} }
func (m *MenuModule) String() string { return proto.CompactTextString(m) }
func (*MenuModule) ProtoMessage()    {}
func (*MenuModule) Descriptor() ([]byte, []int) {
	return fileDescriptor_08a373ad122871df, []int{2}
}

func (m *MenuModule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuModule.Unmarshal(m, b)
}
func (m *MenuModule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuModule.Marshal(b, m, deterministic)
}
func (m *MenuModule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuModule.Merge(m, src)
}
func (m *MenuModule) XXX_Size() int {
	return xxx_messageInfo_MenuModule.Size(m)
}
func (m *MenuModule) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuModule.DiscardUnknown(m)
}

var xxx_messageInfo_MenuModule proto.InternalMessageInfo

func (m *MenuModule) GetModule() Module {
	if m != nil {
		return m.Module
	}
	return Module__Module
}

type Cascade struct {
	Value                int64      `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Label                string     `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Children             []*Cascade `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	Child                []*Cascade `protobuf:"bytes,4,rep,name=child,proto3" json:"child,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Cascade) Reset()         { *m = Cascade{} }
func (m *Cascade) String() string { return proto.CompactTextString(m) }
func (*Cascade) ProtoMessage()    {}
func (*Cascade) Descriptor() ([]byte, []int) {
	return fileDescriptor_08a373ad122871df, []int{3}
}

func (m *Cascade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cascade.Unmarshal(m, b)
}
func (m *Cascade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cascade.Marshal(b, m, deterministic)
}
func (m *Cascade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cascade.Merge(m, src)
}
func (m *Cascade) XXX_Size() int {
	return xxx_messageInfo_Cascade.Size(m)
}
func (m *Cascade) XXX_DiscardUnknown() {
	xxx_messageInfo_Cascade.DiscardUnknown(m)
}

var xxx_messageInfo_Cascade proto.InternalMessageInfo

func (m *Cascade) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Cascade) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Cascade) GetChildren() []*Cascade {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *Cascade) GetChild() []*Cascade {
	if m != nil {
		return m.Child
	}
	return nil
}

type Cascades struct {
	Cascades             []*Cascade `protobuf:"bytes,1,rep,name=cascades,proto3" json:"cascades,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Cascades) Reset()         { *m = Cascades{} }
func (m *Cascades) String() string { return proto.CompactTextString(m) }
func (*Cascades) ProtoMessage()    {}
func (*Cascades) Descriptor() ([]byte, []int) {
	return fileDescriptor_08a373ad122871df, []int{4}
}

func (m *Cascades) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cascades.Unmarshal(m, b)
}
func (m *Cascades) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cascades.Marshal(b, m, deterministic)
}
func (m *Cascades) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cascades.Merge(m, src)
}
func (m *Cascades) XXX_Size() int {
	return xxx_messageInfo_Cascades.Size(m)
}
func (m *Cascades) XXX_DiscardUnknown() {
	xxx_messageInfo_Cascades.DiscardUnknown(m)
}

var xxx_messageInfo_Cascades proto.InternalMessageInfo

func (m *Cascades) GetCascades() []*Cascade {
	if m != nil {
		return m.Cascades
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb_user_v1.Module", Module_name, Module_value)
	proto.RegisterType((*PermissionProto)(nil), "pb_user_v1.PermissionProto")
	proto.RegisterType((*MenuProto)(nil), "pb_user_v1.MenuProto")
	proto.RegisterType((*MenuModule)(nil), "pb_user_v1.MenuModule")
	proto.RegisterType((*Cascade)(nil), "pb_user_v1.Cascade")
	proto.RegisterType((*Cascades)(nil), "pb_user_v1.Cascades")
}

func init() { proto.RegisterFile("permission-msg.proto", fileDescriptor_08a373ad122871df) }

var fileDescriptor_08a373ad122871df = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x65, 0xea, 0xf8, 0x91, 0x9b, 0x02, 0x61, 0xa8, 0x60, 0xa8, 0x84, 0xb0, 0xcc, 0xa2, 0xa6,
	0x12, 0x41, 0x84, 0x0d, 0x12, 0x2b, 0x28, 0x2c, 0x2c, 0x08, 0x44, 0x46, 0xac, 0xad, 0x71, 0xe7,
	0x8a, 0x58, 0xf8, 0xa5, 0xb1, 0xa7, 0xa2, 0x9f, 0xc1, 0x47, 0xf0, 0x65, 0xfc, 0x08, 0x9a, 0x47,
	0x83, 0x85, 0x04, 0xdd, 0xdd, 0x73, 0xee, 0x99, 0x39, 0x27, 0x67, 0x62, 0x38, 0xea, 0x51, 0x36,
	0xd5, 0x30, 0x54, 0x5d, 0xfb, 0xb4, 0x19, 0xbe, 0xae, 0x7a, 0xd9, 0x8d, 0x1d, 0x85, 0xbe, 0x2c,
	0xd4, 0x80, 0xb2, 0xb8, 0x78, 0x7e, 0x0c, 0x25, 0x1f, 0xd0, 0xf2, 0xc9, 0xcf, 0x03, 0xb8, 0xbd,
	0xdd, 0x1f, 0xd8, 0x1a, 0xed, 0x09, 0xf8, 0x55, 0x2b, 0xf0, 0x3b, 0x9b, 0xc7, 0x24, 0x5d, 0xac,
	0xef, 0xac, 0xfe, 0x9c, 0x5d, 0x65, 0x7a, 0x91, 0xdb, 0x3d, 0xbd, 0x0f, 0xa1, 0xe1, 0x2b, 0xc1,
	0x48, 0x4c, 0x52, 0x2f, 0x0f, 0x34, 0xcc, 0x04, 0x7d, 0x00, 0x91, 0x92, 0x55, 0xd1, 0xf2, 0x06,
	0xd9, 0x41, 0x4c, 0xd2, 0x79, 0x1e, 0x2a, 0x59, 0x7d, 0xe4, 0x0d, 0xd2, 0x7b, 0x10, 0x34, 0x38,
	0xee, 0x3a, 0xc1, 0xbc, 0x98, 0xa4, 0x7e, 0xee, 0x10, 0x5d, 0x82, 0xa7, 0x64, 0xc5, 0x66, 0x46,
	0xad, 0x47, 0x7a, 0x0c, 0x91, 0xc4, 0x9a, 0x8f, 0x55, 0xd7, 0x32, 0xdf, 0x68, 0xf7, 0x98, 0x3e,
	0x82, 0x45, 0xa9, 0xc6, 0xb1, 0x6b, 0xad, 0x47, 0x60, 0x4e, 0x81, 0xa5, 0x8c, 0xcd, 0x43, 0x70,
	0xa8, 0xf8, 0x86, 0x97, 0x2c, 0x34, 0xfb, 0xb9, 0x65, 0xde, 0xe3, 0xa5, 0x4e, 0xde, 0x60, 0xab,
	0x74, 0xf2, 0xc8, 0x26, 0xd7, 0x30, 0x13, 0x26, 0x5e, 0x27, 0x54, 0x8d, 0x0c, 0x5c, 0x3c, 0x83,
	0x92, 0x5f, 0x04, 0xe6, 0x1b, 0x6c, 0xd5, 0x5f, 0x0d, 0x91, 0x6b, 0x1a, 0xa2, 0x30, 0x9b, 0x94,
	0x60, 0x66, 0x5d, 0x4e, 0xcf, 0x25, 0xb6, 0xda, 0xdc, 0x33, 0xe6, 0xa1, 0xc1, 0x99, 0xa0, 0xa7,
	0x7b, 0x77, 0xdd, 0xc3, 0xad, 0x35, 0x9d, 0x5e, 0xbc, 0x31, 0x9b, 0xab, 0x44, 0xf4, 0x08, 0xfc,
	0x4e, 0x0a, 0x94, 0xa6, 0x1b, 0x2f, 0xb7, 0x80, 0x3e, 0x86, 0x9b, 0x23, 0x36, 0x7d, 0xcd, 0x47,
	0x2c, 0x7a, 0x3e, 0xee, 0x5c, 0x35, 0x87, 0x57, 0xe4, 0x96, 0x8f, 0xbb, 0xe9, 0xbb, 0x85, 0xd3,
	0x77, 0x4b, 0x5e, 0x02, 0xe8, 0x1f, 0x69, 0x9d, 0x26, 0x69, 0xc8, 0x75, 0x69, 0x92, 0x1f, 0x04,
	0xc2, 0x33, 0x3e, 0x9c, 0x73, 0x61, 0x92, 0x5d, 0xf0, 0x5a, 0xa1, 0xfb, 0x53, 0x58, 0xa0, 0xd9,
	0x9a, 0x97, 0x58, 0xbb, 0x2e, 0x2c, 0xa0, 0xcf, 0x20, 0x3a, 0xdf, 0x55, 0xb5, 0x90, 0xd8, 0x32,
	0x2f, 0xf6, 0xd2, 0xc5, 0xfa, 0xee, 0xd4, 0xc5, 0x5d, 0x99, 0xef, 0x45, 0xf4, 0x09, 0xf8, 0x66,
	0x66, 0xb3, 0x7f, 0xab, 0xad, 0x22, 0x79, 0x05, 0x91, 0x63, 0x06, 0xe3, 0xe3, 0x66, 0x46, 0xfe,
	0xe7, 0xe3, 0x44, 0xa7, 0x27, 0x10, 0xb8, 0x1a, 0x16, 0x10, 0x16, 0x76, 0x5c, 0xde, 0xa0, 0x4b,
	0x38, 0xdc, 0x7c, 0x7a, 0xfb, 0xe5, 0xc3, 0xbb, 0xe2, 0xcd, 0xeb, 0xcf, 0xd9, 0xd9, 0x92, 0x94,
	0x81, 0xf9, 0x90, 0x5e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xfa, 0xb2, 0xe9, 0x78, 0x03,
	0x00, 0x00,
}
