// Code generated by protoc-gen-go. DO NOT EDIT.
// source: role-msg.proto

package pb_user_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoleProto struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	DataPermit           int32    `protobuf:"varint,3,opt,name=data_permit,json=dataPermit,proto3" json:"data_permit,omitempty"`
	Status               int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Id                   int64    `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Ids                  []int64  `protobuf:"varint,7,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleProto) Reset()         { *m = RoleProto{} }
func (m *RoleProto) String() string { return proto.CompactTextString(m) }
func (*RoleProto) ProtoMessage()    {}
func (*RoleProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a27634faf0e2c2b, []int{0}
}

func (m *RoleProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleProto.Unmarshal(m, b)
}
func (m *RoleProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleProto.Marshal(b, m, deterministic)
}
func (m *RoleProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleProto.Merge(m, src)
}
func (m *RoleProto) XXX_Size() int {
	return xxx_messageInfo_RoleProto.Size(m)
}
func (m *RoleProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleProto.DiscardUnknown(m)
}

var xxx_messageInfo_RoleProto proto.InternalMessageInfo

func (m *RoleProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleProto) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *RoleProto) GetDataPermit() int32 {
	if m != nil {
		return m.DataPermit
	}
	return 0
}

func (m *RoleProto) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RoleProto) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoleProto) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *RoleProto) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type RoleMenuPermissionProto struct {
	RoleId               int64    `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	MenuId               int64    `protobuf:"varint,2,opt,name=menu_id,json=menuId,proto3" json:"menu_id,omitempty"`
	PermissionId         int64    `protobuf:"varint,3,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleMenuPermissionProto) Reset()         { *m = RoleMenuPermissionProto{} }
func (m *RoleMenuPermissionProto) String() string { return proto.CompactTextString(m) }
func (*RoleMenuPermissionProto) ProtoMessage()    {}
func (*RoleMenuPermissionProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a27634faf0e2c2b, []int{1}
}

func (m *RoleMenuPermissionProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleMenuPermissionProto.Unmarshal(m, b)
}
func (m *RoleMenuPermissionProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleMenuPermissionProto.Marshal(b, m, deterministic)
}
func (m *RoleMenuPermissionProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleMenuPermissionProto.Merge(m, src)
}
func (m *RoleMenuPermissionProto) XXX_Size() int {
	return xxx_messageInfo_RoleMenuPermissionProto.Size(m)
}
func (m *RoleMenuPermissionProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleMenuPermissionProto.DiscardUnknown(m)
}

var xxx_messageInfo_RoleMenuPermissionProto proto.InternalMessageInfo

func (m *RoleMenuPermissionProto) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *RoleMenuPermissionProto) GetMenuId() int64 {
	if m != nil {
		return m.MenuId
	}
	return 0
}

func (m *RoleMenuPermissionProto) GetPermissionId() int64 {
	if m != nil {
		return m.PermissionId
	}
	return 0
}

type CreateMenuPermRequestProto struct {
	Id                   int64                      `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string                     `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	DataPermit           int32                      `protobuf:"varint,3,opt,name=data_permit,json=dataPermit,proto3" json:"data_permit,omitempty"`
	Status               int32                      `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	RoleMenuPermissions  []*RoleMenuPermissionProto `protobuf:"bytes,5,rep,name=role_menu_permissions,json=roleMenuPermissions,proto3" json:"role_menu_permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CreateMenuPermRequestProto) Reset()         { *m = CreateMenuPermRequestProto{} }
func (m *CreateMenuPermRequestProto) String() string { return proto.CompactTextString(m) }
func (*CreateMenuPermRequestProto) ProtoMessage()    {}
func (*CreateMenuPermRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a27634faf0e2c2b, []int{2}
}

func (m *CreateMenuPermRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMenuPermRequestProto.Unmarshal(m, b)
}
func (m *CreateMenuPermRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMenuPermRequestProto.Marshal(b, m, deterministic)
}
func (m *CreateMenuPermRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMenuPermRequestProto.Merge(m, src)
}
func (m *CreateMenuPermRequestProto) XXX_Size() int {
	return xxx_messageInfo_CreateMenuPermRequestProto.Size(m)
}
func (m *CreateMenuPermRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMenuPermRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMenuPermRequestProto proto.InternalMessageInfo

func (m *CreateMenuPermRequestProto) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateMenuPermRequestProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateMenuPermRequestProto) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *CreateMenuPermRequestProto) GetDataPermit() int32 {
	if m != nil {
		return m.DataPermit
	}
	return 0
}

func (m *CreateMenuPermRequestProto) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateMenuPermRequestProto) GetRoleMenuPermissions() []*RoleMenuPermissionProto {
	if m != nil {
		return m.RoleMenuPermissions
	}
	return nil
}

type RolePageRequestProto struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Page                 *Page        `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Roles                []*RoleProto `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RolePageRequestProto) Reset()         { *m = RolePageRequestProto{} }
func (m *RolePageRequestProto) String() string { return proto.CompactTextString(m) }
func (*RolePageRequestProto) ProtoMessage()    {}
func (*RolePageRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a27634faf0e2c2b, []int{3}
}

func (m *RolePageRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RolePageRequestProto.Unmarshal(m, b)
}
func (m *RolePageRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RolePageRequestProto.Marshal(b, m, deterministic)
}
func (m *RolePageRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RolePageRequestProto.Merge(m, src)
}
func (m *RolePageRequestProto) XXX_Size() int {
	return xxx_messageInfo_RolePageRequestProto.Size(m)
}
func (m *RolePageRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RolePageRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_RolePageRequestProto proto.InternalMessageInfo

func (m *RolePageRequestProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RolePageRequestProto) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *RolePageRequestProto) GetRoles() []*RoleProto {
	if m != nil {
		return m.Roles
	}
	return nil
}

func init() {
	proto.RegisterType((*RoleProto)(nil), "pb_user_v1.RoleProto")
	proto.RegisterType((*RoleMenuPermissionProto)(nil), "pb_user_v1.RoleMenuPermissionProto")
	proto.RegisterType((*CreateMenuPermRequestProto)(nil), "pb_user_v1.CreateMenuPermRequestProto")
	proto.RegisterType((*RolePageRequestProto)(nil), "pb_user_v1.RolePageRequestProto")
}

func init() { proto.RegisterFile("role-msg.proto", fileDescriptor_3a27634faf0e2c2b) }

var fileDescriptor_3a27634faf0e2c2b = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xcd, 0x6a, 0xe3, 0x30,
	0x14, 0x85, 0xb1, 0x15, 0x3b, 0xe4, 0x66, 0x26, 0x04, 0xcd, 0x64, 0x22, 0x02, 0xc3, 0x18, 0x67,
	0x16, 0x86, 0xd2, 0x40, 0xd3, 0x27, 0x28, 0x5d, 0x65, 0x51, 0x08, 0xda, 0x74, 0x69, 0x94, 0xea,
	0x12, 0x4c, 0xe3, 0x9f, 0x4a, 0x72, 0x77, 0x7d, 0xa8, 0xbe, 0x56, 0x9f, 0xa2, 0xe8, 0x3a, 0x4d,
	0xfa, 0xbb, 0xed, 0x4e, 0xf7, 0x1c, 0xc9, 0xe7, 0x7c, 0xb2, 0x60, 0x64, 0xea, 0x1d, 0x9e, 0x96,
	0x76, 0xbb, 0x68, 0x4c, 0xed, 0x6a, 0x0e, 0xcd, 0x26, 0x6f, 0x2d, 0x9a, 0xfc, 0xfe, 0x6c, 0x06,
	0x1b, 0x65, 0xb1, 0xd3, 0xd3, 0xc7, 0x00, 0x06, 0xb2, 0xde, 0xe1, 0x9a, 0x76, 0x71, 0xe8, 0x55,
	0xaa, 0x44, 0x11, 0x24, 0x41, 0x36, 0x90, 0xb4, 0xe6, 0x7f, 0x20, 0x36, 0x58, 0x2a, 0x73, 0x2b,
	0x42, 0x52, 0xf7, 0x13, 0xff, 0x07, 0x43, 0xad, 0x9c, 0xca, 0x1b, 0x34, 0x65, 0xe1, 0x04, 0x4b,
	0x82, 0x2c, 0x92, 0xe0, 0xa5, 0x35, 0x29, 0xfe, 0xa0, 0x75, 0xca, 0xb5, 0x56, 0xf4, 0xc8, 0xdb,
	0x4f, 0x7c, 0x04, 0x61, 0xa1, 0x45, 0x94, 0x04, 0x19, 0x93, 0x61, 0xa1, 0xf9, 0x5f, 0x80, 0x1b,
	0x83, 0xca, 0xa1, 0xce, 0x95, 0x13, 0x31, 0x85, 0x0c, 0xf6, 0xca, 0x85, 0xe3, 0x63, 0x60, 0x85,
	0xb6, 0xa2, 0x9f, 0xb0, 0x8c, 0x49, 0xbf, 0x4c, 0x1b, 0x98, 0xfa, 0xca, 0x57, 0x58, 0xb5, 0x14,
	0x65, 0x6d, 0x51, 0x57, 0x1d, 0xc0, 0x14, 0xfa, 0x1e, 0x3c, 0x2f, 0x34, 0x31, 0x30, 0x19, 0xfb,
	0x71, 0xa5, 0xbd, 0x51, 0x62, 0xd5, 0x7a, 0x23, 0xec, 0x0c, 0x3f, 0xae, 0x34, 0x9f, 0xc3, 0xcf,
	0xe6, 0xf0, 0x11, 0x6f, 0x33, 0xb2, 0x7f, 0x1c, 0xc5, 0x95, 0x4e, 0x9f, 0x02, 0x98, 0x5d, 0x52,
	0xa3, 0x97, 0x50, 0x89, 0x77, 0x2d, 0x5a, 0xd7, 0xa5, 0x76, 0x44, 0xf1, 0x81, 0xe8, 0x5b, 0xae,
	0xf1, 0x1a, 0x26, 0x84, 0x4a, 0x58, 0xc7, 0xb6, 0x56, 0x44, 0x09, 0xcb, 0x86, 0xcb, 0xf9, 0xe2,
	0xf8, 0xc7, 0x17, 0x5f, 0x5c, 0x97, 0xfc, 0x65, 0x3e, 0x18, 0x36, 0x7d, 0x80, 0xdf, 0xf4, 0x22,
	0xd4, 0x16, 0xdf, 0x50, 0x7e, 0x46, 0xf5, 0x1f, 0x7a, 0x8d, 0xda, 0x22, 0x31, 0x0d, 0x97, 0xe3,
	0xd7, 0x99, 0x74, 0x9e, 0x5c, 0x7e, 0x02, 0x91, 0x0f, 0xb2, 0x82, 0x51, 0xb5, 0xc9, 0xfb, 0x6a,
	0x5d, 0x99, 0x6e, 0xcf, 0x26, 0xa6, 0x87, 0x79, 0xfe, 0x1c, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x11,
	0x72, 0x42, 0xc2, 0x02, 0x00, 0x00,
}
