// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-msg.proto

package pb_user_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserProto struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProto) Reset()         { *m = UserProto{} }
func (m *UserProto) String() string { return proto.CompactTextString(m) }
func (*UserProto) ProtoMessage()    {}
func (*UserProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_776ecf2b3b02e2ad, []int{0}
}

func (m *UserProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProto.Unmarshal(m, b)
}
func (m *UserProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProto.Marshal(b, m, deterministic)
}
func (m *UserProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProto.Merge(m, src)
}
func (m *UserProto) XXX_Size() int {
	return xxx_messageInfo_UserProto.Size(m)
}
func (m *UserProto) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProto.DiscardUnknown(m)
}

var xxx_messageInfo_UserProto proto.InternalMessageInfo

func (m *UserProto) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserProto) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func init() {
	proto.RegisterType((*UserProto)(nil), "pb_user_v1.UserProto")
}

func init() { proto.RegisterFile("user-msg.proto", fileDescriptor_776ecf2b3b02e2ad) }

var fileDescriptor_776ecf2b3b02e2ad = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x2d, 0x4e, 0x2d,
	0xd2, 0xcd, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2a, 0x48, 0x8a, 0x07,
	0x09, 0xc5, 0x97, 0x19, 0x2a, 0x39, 0x72, 0x71, 0x86, 0x16, 0xa7, 0x16, 0x05, 0x80, 0x25, 0xc4,
	0xb9, 0xd8, 0xc1, 0xe2, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x6c, 0x20, 0xae,
	0x67, 0x8a, 0x90, 0x34, 0x17, 0x27, 0x58, 0x22, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x49, 0x81, 0x51,
	0x83, 0x33, 0x88, 0x03, 0x24, 0xe0, 0x97, 0x98, 0x9b, 0x9a, 0xc4, 0x06, 0x36, 0xd5, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x5f, 0x28, 0x56, 0x96, 0x67, 0x00, 0x00, 0x00,
}
