// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-msg.proto

package pb_user_v1 // import "."

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AddUserRequest 添加用户请求
type UserProto struct {
	Id                   *Index   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mobile               int64    `protobuf:"varint,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	RoleIds              []*Index `protobuf:"bytes,5,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProto) Reset()         { *m = UserProto{} }
func (m *UserProto) String() string { return proto.CompactTextString(m) }
func (*UserProto) ProtoMessage()    {}
func (*UserProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_msg_884e7b459da2dfd9, []int{0}
}
func (m *UserProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProto.Unmarshal(m, b)
}
func (m *UserProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProto.Marshal(b, m, deterministic)
}
func (dst *UserProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProto.Merge(dst, src)
}
func (m *UserProto) XXX_Size() int {
	return xxx_messageInfo_UserProto.Size(m)
}
func (m *UserProto) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProto.DiscardUnknown(m)
}

var xxx_messageInfo_UserProto proto.InternalMessageInfo

func (m *UserProto) GetId() *Index {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UserProto) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserProto) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UserProto) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserProto) GetMobile() int64 {
	if m != nil {
		return m.Mobile
	}
	return 0
}

func (m *UserProto) GetRoleIds() []*Index {
	if m != nil {
		return m.RoleIds
	}
	return nil
}

type Index struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_msg_884e7b459da2dfd9, []int{1}
}
func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (dst *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(dst, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// UserResponse 用户响应
type NullResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullResponse) Reset()         { *m = NullResponse{} }
func (m *NullResponse) String() string { return proto.CompactTextString(m) }
func (*NullResponse) ProtoMessage()    {}
func (*NullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_msg_884e7b459da2dfd9, []int{2}
}
func (m *NullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullResponse.Unmarshal(m, b)
}
func (m *NullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullResponse.Marshal(b, m, deterministic)
}
func (dst *NullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullResponse.Merge(dst, src)
}
func (m *NullResponse) XXX_Size() int {
	return xxx_messageInfo_NullResponse.Size(m)
}
func (m *NullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NullResponse proto.InternalMessageInfo

func (m *NullResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*UserProto)(nil), "UserProto")
	proto.RegisterType((*Index)(nil), "Index")
	proto.RegisterType((*NullResponse)(nil), "NullResponse")
}

func init() { proto.RegisterFile("user-msg.proto", fileDescriptor_user_msg_884e7b459da2dfd9) }

var fileDescriptor_user_msg_884e7b459da2dfd9 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0xd9, 0xe4, 0x2e, 0x26, 0xe3, 0x91, 0x62, 0x8b, 0x73, 0x51, 0x84, 0x98, 0x2a, 0x8d,
	0x01, 0xb5, 0xb4, 0xd3, 0xea, 0x9a, 0x43, 0x02, 0x36, 0x36, 0x21, 0x61, 0x87, 0x63, 0x61, 0x93,
	0x09, 0x3b, 0x9e, 0xfa, 0xcb, 0xfc, 0x7d, 0x92, 0xb9, 0x08, 0xd7, 0xcd, 0xfb, 0xde, 0x3c, 0x78,
	0x33, 0x90, 0x1f, 0x19, 0xc3, 0xfd, 0xc0, 0x87, 0x7a, 0x0a, 0xf4, 0x49, 0xe5, 0xaf, 0x82, 0xec,
	0x9d, 0x31, 0xbc, 0xcd, 0x4a, 0x6f, 0x21, 0x72, 0xd6, 0x24, 0x85, 0xaa, 0x2e, 0x1f, 0x93, 0x7a,
	0x37, 0x5a, 0xfc, 0x69, 0x22, 0x67, 0xf5, 0x0d, 0x64, 0x73, 0xae, 0x1d, 0xbb, 0x01, 0x8d, 0x2a,
	0x54, 0x95, 0x35, 0xe9, 0x0c, 0xf6, 0xdd, 0x80, 0xfa, 0x16, 0xc0, 0xd3, 0xc1, 0x8d, 0x27, 0x37,
	0x12, 0x37, 0x13, 0x22, 0xf6, 0x35, 0xa4, 0x53, 0xc7, 0xfc, 0x4d, 0xc1, 0x9a, 0xf8, 0x14, 0xfd,
	0xd7, 0x7a, 0x0b, 0xc9, 0x40, 0xbd, 0xf3, 0x68, 0x56, 0x85, 0xaa, 0xe2, 0x66, 0x51, 0xfa, 0x0e,
	0xd2, 0x40, 0x1e, 0x5b, 0x67, 0xd9, 0xac, 0x8b, 0xf8, 0xac, 0xcd, 0xc5, 0xcc, 0x77, 0x96, 0xcb,
	0x2b, 0x58, 0x0b, 0xd1, 0xb9, 0x74, 0x56, 0x92, 0x8f, 0x9c, 0x2d, 0x4b, 0xd8, 0xec, 0x8f, 0xde,
	0x37, 0xc8, 0x13, 0x8d, 0x8c, 0x5a, 0xc3, 0xea, 0x95, 0x2c, 0x2e, 0x1b, 0x32, 0xbf, 0xe4, 0x1f,
	0x9b, 0xfa, 0x79, 0xea, 0x5b, 0x39, 0xea, 0xeb, 0xa1, 0x4f, 0xe4, 0x19, 0x4f, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x35, 0x0d, 0x6c, 0x7a, 0x1e, 0x01, 0x00, 0x00,
}
