// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-msg.proto

package pb_user_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AddUserRequest 添加用户请求
type UserProto struct {
	Id                   *Index   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	GroupId              int64    `protobuf:"varint,7,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserType             int64    `protobuf:"varint,8,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	RoleIds              []*Index `protobuf:"bytes,5,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	Ststus               int64    `protobuf:"varint,9,opt,name=ststus,proto3" json:"ststus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProto) Reset()         { *m = UserProto{} }
func (m *UserProto) String() string { return proto.CompactTextString(m) }
func (*UserProto) ProtoMessage()    {}
func (*UserProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_776ecf2b3b02e2ad, []int{0}
}

func (m *UserProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProto.Unmarshal(m, b)
}
func (m *UserProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProto.Marshal(b, m, deterministic)
}
func (m *UserProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProto.Merge(m, src)
}
func (m *UserProto) XXX_Size() int {
	return xxx_messageInfo_UserProto.Size(m)
}
func (m *UserProto) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProto.DiscardUnknown(m)
}

var xxx_messageInfo_UserProto proto.InternalMessageInfo

func (m *UserProto) GetId() *Index {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UserProto) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserProto) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UserProto) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserProto) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserProto) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *UserProto) GetUserType() int64 {
	if m != nil {
		return m.UserType
	}
	return 0
}

func (m *UserProto) GetRoleIds() []*Index {
	if m != nil {
		return m.RoleIds
	}
	return nil
}

func (m *UserProto) GetStstus() int64 {
	if m != nil {
		return m.Ststus
	}
	return 0
}

type UserRoleProto struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleIds              string   `protobuf:"bytes,2,opt,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRoleProto) Reset()         { *m = UserRoleProto{} }
func (m *UserRoleProto) String() string { return proto.CompactTextString(m) }
func (*UserRoleProto) ProtoMessage()    {}
func (*UserRoleProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_776ecf2b3b02e2ad, []int{1}
}

func (m *UserRoleProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRoleProto.Unmarshal(m, b)
}
func (m *UserRoleProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRoleProto.Marshal(b, m, deterministic)
}
func (m *UserRoleProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRoleProto.Merge(m, src)
}
func (m *UserRoleProto) XXX_Size() int {
	return xxx_messageInfo_UserRoleProto.Size(m)
}
func (m *UserRoleProto) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRoleProto.DiscardUnknown(m)
}

var xxx_messageInfo_UserRoleProto proto.InternalMessageInfo

func (m *UserRoleProto) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserRoleProto) GetRoleIds() string {
	if m != nil {
		return m.RoleIds
	}
	return ""
}

type Users struct {
	Users                []*UserProto `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_776ecf2b3b02e2ad, []int{2}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*UserProto {
	if m != nil {
		return m.Users
	}
	return nil
}

type AddUsersRequest struct {
	Users                []*UserProto `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	IsCover              int32        `protobuf:"varint,2,opt,name=is_cover,json=isCover,proto3" json:"is_cover,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddUsersRequest) Reset()         { *m = AddUsersRequest{} }
func (m *AddUsersRequest) String() string { return proto.CompactTextString(m) }
func (*AddUsersRequest) ProtoMessage()    {}
func (*AddUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_776ecf2b3b02e2ad, []int{3}
}

func (m *AddUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUsersRequest.Unmarshal(m, b)
}
func (m *AddUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUsersRequest.Marshal(b, m, deterministic)
}
func (m *AddUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUsersRequest.Merge(m, src)
}
func (m *AddUsersRequest) XXX_Size() int {
	return xxx_messageInfo_AddUsersRequest.Size(m)
}
func (m *AddUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUsersRequest proto.InternalMessageInfo

func (m *AddUsersRequest) GetUsers() []*UserProto {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *AddUsersRequest) GetIsCover() int32 {
	if m != nil {
		return m.IsCover
	}
	return 0
}

type UsersPage struct {
	Users                *Users   `protobuf:"bytes,1,opt,name=users,proto3" json:"users,omitempty"`
	Page                 *Page    `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersPage) Reset()         { *m = UsersPage{} }
func (m *UsersPage) String() string { return proto.CompactTextString(m) }
func (*UsersPage) ProtoMessage()    {}
func (*UsersPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_776ecf2b3b02e2ad, []int{4}
}

func (m *UsersPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersPage.Unmarshal(m, b)
}
func (m *UsersPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersPage.Marshal(b, m, deterministic)
}
func (m *UsersPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersPage.Merge(m, src)
}
func (m *UsersPage) XXX_Size() int {
	return xxx_messageInfo_UsersPage.Size(m)
}
func (m *UsersPage) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersPage.DiscardUnknown(m)
}

var xxx_messageInfo_UsersPage proto.InternalMessageInfo

func (m *UsersPage) GetUsers() *Users {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *UsersPage) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type UserPage struct {
	User                 *UserProto `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Page                 *Page      `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserPage) Reset()         { *m = UserPage{} }
func (m *UserPage) String() string { return proto.CompactTextString(m) }
func (*UserPage) ProtoMessage()    {}
func (*UserPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_776ecf2b3b02e2ad, []int{5}
}

func (m *UserPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPage.Unmarshal(m, b)
}
func (m *UserPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPage.Marshal(b, m, deterministic)
}
func (m *UserPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPage.Merge(m, src)
}
func (m *UserPage) XXX_Size() int {
	return xxx_messageInfo_UserPage.Size(m)
}
func (m *UserPage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPage.DiscardUnknown(m)
}

var xxx_messageInfo_UserPage proto.InternalMessageInfo

func (m *UserPage) GetUser() *UserProto {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserPage) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type UserIDs struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserIDs) Reset()         { *m = UserIDs{} }
func (m *UserIDs) String() string { return proto.CompactTextString(m) }
func (*UserIDs) ProtoMessage()    {}
func (*UserIDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_776ecf2b3b02e2ad, []int{6}
}

func (m *UserIDs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIDs.Unmarshal(m, b)
}
func (m *UserIDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIDs.Marshal(b, m, deterministic)
}
func (m *UserIDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIDs.Merge(m, src)
}
func (m *UserIDs) XXX_Size() int {
	return xxx_messageInfo_UserIDs.Size(m)
}
func (m *UserIDs) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIDs.DiscardUnknown(m)
}

var xxx_messageInfo_UserIDs proto.InternalMessageInfo

func (m *UserIDs) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GroupUserIds struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserIds              []int64  `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupUserIds) Reset()         { *m = GroupUserIds{} }
func (m *GroupUserIds) String() string { return proto.CompactTextString(m) }
func (*GroupUserIds) ProtoMessage()    {}
func (*GroupUserIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_776ecf2b3b02e2ad, []int{7}
}

func (m *GroupUserIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupUserIds.Unmarshal(m, b)
}
func (m *GroupUserIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupUserIds.Marshal(b, m, deterministic)
}
func (m *GroupUserIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupUserIds.Merge(m, src)
}
func (m *GroupUserIds) XXX_Size() int {
	return xxx_messageInfo_GroupUserIds.Size(m)
}
func (m *GroupUserIds) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupUserIds.DiscardUnknown(m)
}

var xxx_messageInfo_GroupUserIds proto.InternalMessageInfo

func (m *GroupUserIds) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupUserIds) GetUserIds() []int64 {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type UsersProto struct {
	Id                   *Index   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	GroupId              int64    `protobuf:"varint,7,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserType             int64    `protobuf:"varint,8,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	RoleIds              []int64  `protobuf:"varint,5,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	Ststus               int64    `protobuf:"varint,9,opt,name=ststus,proto3" json:"ststus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersProto) Reset()         { *m = UsersProto{} }
func (m *UsersProto) String() string { return proto.CompactTextString(m) }
func (*UsersProto) ProtoMessage()    {}
func (*UsersProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_776ecf2b3b02e2ad, []int{8}
}

func (m *UsersProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersProto.Unmarshal(m, b)
}
func (m *UsersProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersProto.Marshal(b, m, deterministic)
}
func (m *UsersProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersProto.Merge(m, src)
}
func (m *UsersProto) XXX_Size() int {
	return xxx_messageInfo_UsersProto.Size(m)
}
func (m *UsersProto) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersProto.DiscardUnknown(m)
}

var xxx_messageInfo_UsersProto proto.InternalMessageInfo

func (m *UsersProto) GetId() *Index {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UsersProto) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UsersProto) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UsersProto) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UsersProto) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UsersProto) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *UsersProto) GetUserType() int64 {
	if m != nil {
		return m.UserType
	}
	return 0
}

func (m *UsersProto) GetRoleIds() []int64 {
	if m != nil {
		return m.RoleIds
	}
	return nil
}

func (m *UsersProto) GetStstus() int64 {
	if m != nil {
		return m.Ststus
	}
	return 0
}

type UserQueryCondition struct {
	Id                   []int64  `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	GroupId              []int64  `protobuf:"varint,3,rep,packed,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	PageNum              int64    `protobuf:"varint,4,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize             int64    `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserQueryCondition) Reset()         { *m = UserQueryCondition{} }
func (m *UserQueryCondition) String() string { return proto.CompactTextString(m) }
func (*UserQueryCondition) ProtoMessage()    {}
func (*UserQueryCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_776ecf2b3b02e2ad, []int{9}
}

func (m *UserQueryCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserQueryCondition.Unmarshal(m, b)
}
func (m *UserQueryCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserQueryCondition.Marshal(b, m, deterministic)
}
func (m *UserQueryCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserQueryCondition.Merge(m, src)
}
func (m *UserQueryCondition) XXX_Size() int {
	return xxx_messageInfo_UserQueryCondition.Size(m)
}
func (m *UserQueryCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_UserQueryCondition.DiscardUnknown(m)
}

var xxx_messageInfo_UserQueryCondition proto.InternalMessageInfo

func (m *UserQueryCondition) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UserQueryCondition) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UserQueryCondition) GetGroupId() []int64 {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *UserQueryCondition) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *UserQueryCondition) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type UserQueryResult struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	GroupName            string   `protobuf:"bytes,5,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Mobile               string   `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile,omitempty"`
	GroupId              int64    `protobuf:"varint,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	RoleName             []string `protobuf:"bytes,7,rep,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserQueryResult) Reset()         { *m = UserQueryResult{} }
func (m *UserQueryResult) String() string { return proto.CompactTextString(m) }
func (*UserQueryResult) ProtoMessage()    {}
func (*UserQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_776ecf2b3b02e2ad, []int{10}
}

func (m *UserQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserQueryResult.Unmarshal(m, b)
}
func (m *UserQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserQueryResult.Marshal(b, m, deterministic)
}
func (m *UserQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserQueryResult.Merge(m, src)
}
func (m *UserQueryResult) XXX_Size() int {
	return xxx_messageInfo_UserQueryResult.Size(m)
}
func (m *UserQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UserQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_UserQueryResult proto.InternalMessageInfo

func (m *UserQueryResult) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserQueryResult) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UserQueryResult) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *UserQueryResult) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserQueryResult) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *UserQueryResult) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserQueryResult) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *UserQueryResult) GetRoleName() []string {
	if m != nil {
		return m.RoleName
	}
	return nil
}

type UserQueryResponse struct {
	Total                int64              `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PageNum              int64              `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize             int64              `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	UserQueryResult      []*UserQueryResult `protobuf:"bytes,4,rep,name=userQueryResult,proto3" json:"userQueryResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UserQueryResponse) Reset()         { *m = UserQueryResponse{} }
func (m *UserQueryResponse) String() string { return proto.CompactTextString(m) }
func (*UserQueryResponse) ProtoMessage()    {}
func (*UserQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_776ecf2b3b02e2ad, []int{11}
}

func (m *UserQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserQueryResponse.Unmarshal(m, b)
}
func (m *UserQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserQueryResponse.Marshal(b, m, deterministic)
}
func (m *UserQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserQueryResponse.Merge(m, src)
}
func (m *UserQueryResponse) XXX_Size() int {
	return xxx_messageInfo_UserQueryResponse.Size(m)
}
func (m *UserQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserQueryResponse proto.InternalMessageInfo

func (m *UserQueryResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *UserQueryResponse) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *UserQueryResponse) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *UserQueryResponse) GetUserQueryResult() []*UserQueryResult {
	if m != nil {
		return m.UserQueryResult
	}
	return nil
}

func init() {
	proto.RegisterType((*UserProto)(nil), "pb_user_v1.UserProto")
	proto.RegisterType((*UserRoleProto)(nil), "pb_user_v1.UserRoleProto")
	proto.RegisterType((*Users)(nil), "pb_user_v1.Users")
	proto.RegisterType((*AddUsersRequest)(nil), "pb_user_v1.AddUsersRequest")
	proto.RegisterType((*UsersPage)(nil), "pb_user_v1.UsersPage")
	proto.RegisterType((*UserPage)(nil), "pb_user_v1.UserPage")
	proto.RegisterType((*UserIDs)(nil), "pb_user_v1.UserIDs")
	proto.RegisterType((*GroupUserIds)(nil), "pb_user_v1.GroupUserIds")
	proto.RegisterType((*UsersProto)(nil), "pb_user_v1.UsersProto")
	proto.RegisterType((*UserQueryCondition)(nil), "pb_user_v1.UserQueryCondition")
	proto.RegisterType((*UserQueryResult)(nil), "pb_user_v1.UserQueryResult")
	proto.RegisterType((*UserQueryResponse)(nil), "pb_user_v1.UserQueryResponse")
}

func init() { proto.RegisterFile("user-msg.proto", fileDescriptor_776ecf2b3b02e2ad) }

var fileDescriptor_776ecf2b3b02e2ad = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x55, 0x5b, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0xe3, 0x38, 0x76, 0x6e, 0xa1, 0x8f, 0x11, 0x0f, 0xb7, 0x55, 0xa5, 0x60, 0x21, 0x51,
	0x04, 0x54, 0xa2, 0xb0, 0x81, 0xaa, 0x45, 0x28, 0x3f, 0x55, 0x19, 0xe0, 0x03, 0xf8, 0xb0, 0x9c,
	0xce, 0x28, 0x1a, 0x29, 0xf6, 0x18, 0xcf, 0xb8, 0xd0, 0x2e, 0x81, 0x05, 0xf0, 0xc5, 0x02, 0xd8,
	0x1b, 0x9b, 0x40, 0xf7, 0x8e, 0x9b, 0xd8, 0x2d, 0xa5, 0xe5, 0x97, 0xbf, 0xdc, 0xd7, 0x99, 0x73,
	0xcf, 0x99, 0x89, 0x61, 0xb9, 0x36, 0xb2, 0x7a, 0x96, 0x9b, 0xe9, 0x4e, 0x59, 0x69, 0xab, 0x19,
	0x94, 0x93, 0x14, 0x53, 0xe9, 0xc9, 0xf3, 0x0d, 0x98, 0x64, 0x46, 0xba, 0x7c, 0xf2, 0xa3, 0x07,
	0xc3, 0xf7, 0x46, 0x56, 0x47, 0xd4, 0xf5, 0x00, 0x7a, 0x4a, 0xc4, 0x83, 0x91, 0xb7, 0xbd, 0xb4,
	0xbb, 0xb6, 0xb3, 0x18, 0xd9, 0x19, 0x17, 0x42, 0x7e, 0xe5, 0x3d, 0x25, 0xd8, 0x26, 0x0c, 0x29,
	0x59, 0x64, 0xb9, 0x8c, 0xbd, 0x91, 0xb7, 0x3d, 0xe4, 0x11, 0x26, 0x0e, 0xb3, 0x5c, 0xb2, 0x2d,
	0x80, 0x99, 0x9e, 0xaa, 0xc2, 0x55, 0x7b, 0x54, 0x1d, 0x52, 0x86, 0xca, 0x1b, 0x10, 0x95, 0x99,
	0x31, 0x5f, 0x74, 0x25, 0x62, 0xdf, 0x8d, 0x9e, 0xc7, 0xec, 0x1e, 0x0c, 0x72, 0x3d, 0x51, 0x33,
	0x19, 0xf7, 0xa9, 0xd2, 0x44, 0x6c, 0x1d, 0xa2, 0x69, 0xa5, 0xeb, 0x32, 0x55, 0x22, 0x0e, 0x47,
	0xde, 0xb6, 0xcf, 0x43, 0x8a, 0xc7, 0x0b, 0x2a, 0xf6, 0xb4, 0x94, 0x71, 0x44, 0x35, 0xa2, 0xf2,
	0xee, 0xb4, 0x94, 0xec, 0x29, 0x44, 0x95, 0x9e, 0xc9, 0x54, 0x09, 0x13, 0x07, 0x23, 0xff, 0xcf,
	0x0b, 0x85, 0xd8, 0x32, 0x16, 0x06, 0x4f, 0x37, 0xd6, 0xd8, 0xda, 0xc4, 0x43, 0xc2, 0x69, 0xa2,
	0x64, 0x1f, 0x6e, 0xa3, 0x3a, 0x5c, 0xcf, 0xa4, 0x53, 0xe8, 0x3e, 0x84, 0x04, 0xa1, 0x04, 0x2d,
	0xef, 0xf3, 0x01, 0x86, 0x63, 0x81, 0x3c, 0xe7, 0xe7, 0xb9, 0xc5, 0xcf, 0xc1, 0x93, 0x97, 0x10,
	0x20, 0x88, 0x61, 0x4f, 0x20, 0xc0, 0x6e, 0x13, 0x7b, 0x44, 0xe8, 0x6e, 0x9b, 0xd0, 0xdc, 0x04,
	0xee, 0x7a, 0x92, 0x0f, 0xb0, 0xb2, 0x27, 0x04, 0x0d, 0x72, 0xf9, 0xb9, 0x96, 0xc6, 0xfe, 0xd3,
	0x3c, 0x12, 0x52, 0x26, 0x3d, 0xd6, 0x27, 0xb2, 0x22, 0x42, 0x01, 0x0f, 0x95, 0xd9, 0xc7, 0x30,
	0xf9, 0xe8, 0x3c, 0x37, 0x47, 0xd9, 0x54, 0xb2, 0x47, 0x0b, 0xd0, 0x4b, 0xb6, 0xbb, 0xd3, 0x1b,
	0xc0, 0x87, 0xd0, 0x2f, 0xb3, 0xa9, 0xb3, 0x75, 0x69, 0x77, 0xb5, 0xdd, 0x87, 0x40, 0x9c, 0xaa,
	0xc9, 0x27, 0x88, 0x88, 0x0a, 0x42, 0x3f, 0x86, 0x3e, 0x76, 0x34, 0xc8, 0x57, 0xd0, 0xa5, 0x96,
	0x1b, 0x82, 0x6f, 0x42, 0x88, 0x83, 0xe3, 0x03, 0xc3, 0x56, 0xc1, 0x47, 0xa9, 0x51, 0x09, 0x9f,
	0xe3, 0xcf, 0xe4, 0x00, 0x6e, 0xbd, 0xc6, 0x9b, 0x41, 0x1d, 0xc2, 0x74, 0x6e, 0x8e, 0xd7, 0xbd,
	0x39, 0xeb, 0x10, 0x35, 0x2e, 0xa2, 0x59, 0x88, 0x10, 0x3a, 0x1b, 0x4d, 0xf2, 0xad, 0x07, 0xe0,
	0xc4, 0xf9, 0xdf, 0x5e, 0xc4, 0xfa, 0x85, 0x17, 0xe1, 0x5f, 0x7f, 0xfd, 0xbf, 0x7b, 0xc0, 0x50,
	0x8c, 0x37, 0xb5, 0xac, 0x4e, 0xf7, 0x75, 0x21, 0x94, 0x55, 0xba, 0x60, 0xcb, 0x24, 0x8a, 0x93,
	0x1e, 0x15, 0xb8, 0x66, 0xc9, 0x36, 0x61, 0xdf, 0x1d, 0xdc, 0x32, 0x02, 0x8d, 0x4d, 0x8b, 0x3a,
	0xa7, 0x2d, 0x7d, 0x1e, 0x62, 0x7c, 0x58, 0xe7, 0xb8, 0x0b, 0x95, 0x8c, 0x3a, 0x93, 0x71, 0xe0,
	0x76, 0xc1, 0xc4, 0x5b, 0x75, 0x26, 0x93, 0x5f, 0x1e, 0xac, 0xcc, 0x89, 0x71, 0x69, 0xea, 0x99,
	0x9d, 0xb3, 0xf2, 0x6e, 0xc6, 0x6a, 0x0b, 0xe0, 0xb8, 0x92, 0x99, 0x95, 0x22, 0xcd, 0x6c, 0x23,
	0xfe, 0xb0, 0xc9, 0xec, 0xd9, 0xae, 0xab, 0xfd, 0xcb, 0xae, 0xba, 0x8d, 0xa8, 0x1a, 0xb8, 0x59,
	0xca, 0x50, 0x79, 0xe1, 0x5c, 0x74, 0xa5, 0x73, 0x83, 0x4b, 0xce, 0x91, 0x39, 0x04, 0x18, 0x8e,
	0x7c, 0x3c, 0x0e, 0x13, 0x88, 0x97, 0xfc, 0xf4, 0x60, 0xad, 0xbd, 0x6d, 0xa9, 0x0b, 0x23, 0xd9,
	0x1d, 0x08, 0xac, 0xb6, 0xd9, 0xac, 0x59, 0xd9, 0x05, 0x1d, 0x45, 0x7b, 0x7f, 0x51, 0xd4, 0xef,
	0x2a, 0xca, 0x5e, 0xc1, 0x4a, 0xdd, 0x15, 0x34, 0xee, 0xd3, 0xbf, 0xcc, 0xe6, 0xc5, 0x67, 0xdb,
	0x6a, 0xe1, 0x17, 0x67, 0x26, 0x03, 0xfa, 0xac, 0xbc, 0xf8, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x27,
	0x9f, 0x33, 0xa0, 0x80, 0x06, 0x00, 0x00,
}
