mysql:
  host: 106.14.122.162
  port: 3306
  userName: root
  password: +6jtHUesSSU#
  dbName: gdp
  timeZone: Local
  sqlPath: ./resources/sql
<<<<<<< HEAD
etcdHost: 172.18.28.226:2379
=======
etcdHost: 192.168.2.191:2379
>>>>>>> 4817b585fb8fdbd5ee7f0be2f50d9abf17d33d8f
